service: visa-rescheduler-lambda

provider:
  name: aws
  logRetentionInDays: 5
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'iam:PassRole'
          Resource:
            - 'Fn::Join':
                - ''
                - - 'arn:aws:iam::'
                  - Ref: AWS::AccountId
                  - ':role/'
                  - ${self:service}
                  - '-'
                  - ${self:provider.stage}
                  - '-'
                  - Ref: AWS::Region
                  - '-lambdaRole'
        - Effect: Allow
          Action:
            - 'scheduler:GetSchedule'
            - 'scheduler:UpdateSchedule'
          Resource:
            - 'Fn::Join':
              - ''
              - - 'arn:aws:scheduler:'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - ':schedule/default/'
                - ${self:service}
                - '*'


  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  main:
    timeout: 60
    # If you experience any errors such as Chrome crashing or not being available you might need to increase the storage available to your Lambda Function.
    memorySize: 2048
    image:
      name: img
    events:
      - schedule:
          method: scheduler
          rate: rate(${file(./json_var.json):retry_value, '10'} minutes)